comment: sáb 15 mar 2025 00:51:37 CST

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,7 +28,6 @@ jobs:
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
 
-      # Configura Docker Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
@@ -69,13 +68,22 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Debug tags
+      - name: Debug meta outputs
         run: |
-          echo "Generated tags: ${{ steps.meta.outputs.tags }}"
+          echo "Meta outputs:"
+          echo "tags: ${{ steps.meta.outputs.tags }}"
+          echo "labels: ${{ steps.meta.outputs.labels }}"
 
       - name: Extract first tag
         id: extract-tag
         run: |
+          # Verifica si steps.meta.outputs.tags está vacío
+          if [ -z "${{ steps.meta.outputs.tags }}" ]; then
+            echo "Error: No tags generated by docker/metadata-action"
+            exit 1
+          fi
+
+          # Extrae la primera etiqueta de la lista generada por docker/metadata-action
           FIRST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | awk -F, '{print $1}')
           echo "First tag: $FIRST_TAG"
           echo "first_tag=$FIRST_TAG" >> $GITHUB_OUTPUT
